name: Reject Self Approval Action
description: Reject self approved deployments.
author: YUMEMI Inc.
branding:
  icon: alert-triangle
  color: yellow
runs:
  using: node20
  main: 'index.js'
inputs:
  token:
    required: true
    description: GitHub token with actions:read access.
    default: '${{ github.token }}'
  allow-no-reviews:
    required: true
    description: GitHub token with actions:read access.
    default: 'false'
